In [1]:
import string

# Initialize Otter
import otter
grader = otter.Notebook("lab02A.ipynb")

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
%matplotlib inline

## 复习

In [3]:
# 通过传入列的形式创建dataframe
fruit_info = pd.DataFrame(
    data = {'fruit': ['apple', 'orange', 'banana', 'raspberry'],
          'color': ['red', 'orange', 'yellow', 'pink'],
          'price': [1.0, 0.75, 0.35, 0.05]
          })
fruit_info

       fruit   color  price
0      apple     red   1.00
1     orange  orange   0.75
2     banana  yellow   0.35
3  raspberry    pink   0.05

In [4]:
# 通过传入行的形式创建dataframe
fruit_info2 = pd.DataFrame(
    [("red", "apple", 1.0), ("orange", "orange", 0.75), ("yellow", "banana", 0.35),
     ("pink", "raspberry", 0.05)],
    columns = ["color", "fruit", "price"])
fruit_info2

    color      fruit  price
0     red      apple   1.00
1  orange     orange   0.75
2  yellow     banana   0.35
3    pink  raspberry   0.05

可以通过df.to_numpy()将Dataframe转换为二维的numpy数组<br>
DataFrame可以包含异构数据，而Numpy数组只能保存同质数据

In [5]:
numbers = pd.DataFrame({"A":[1, 2, 3], "B":[0, 1, 1]})
numpy_numbers = numbers.to_numpy()

print(type(numpy_numbers))
print(numpy_numbers)
print(numpy_numbers.dtype)

<class 'numpy.ndarray'>
[[1 0]
 [2 1]
 [3 1]]
int64

In [6]:
fruit_info.values

array([['apple', 'red', 1.0],
       ['orange', 'orange', 0.75],
       ['banana', 'yellow', 0.35],
       ['raspberry', 'pink', 0.05]], dtype=object)

In [7]:
fruit_info_sorted = fruit_info.sort_values("price")
fruit_info_sorted

       fruit   color  price
3  raspberry    pink   0.05
2     banana  yellow   0.35
1     orange  orange   0.75
0      apple     red   1.00

In [8]:
fruit_info_sorted.iloc[[0, 2], 0]

3    raspberry
1       orange
Name: fruit, dtype: object

In [9]:
# Here we're providing a list of fruits as single argument to []
fruit_info[["fruit", "color", "price"]]

       fruit   color  price
0      apple     red   1.00
1     orange  orange   0.75
2     banana  yellow   0.35
3  raspberry    pink   0.05

### Q1a 使用`d['new column name'] = ...`新增Dataframe的列

In [10]:
fruit_info['rank1'] = [1, 2, 3, 4]
fruit_info

       fruit   color  price  rank1
0      apple     red   1.00      1
1     orange  orange   0.75      2
2     banana  yellow   0.35      3
3  raspberry    pink   0.05      4

In [11]:
grader.check("q1a")

q1a results: All test cases passed!

### Q1b  使用`d.loc[:, 'new column name'] = ...`新增Dataframe的列

In [12]:
fruit_info.loc[:, 'rank2'] = [1, 2, 3, 4]
fruit_info

       fruit   color  price  rank1  rank2
0      apple     red   1.00      1      1
1     orange  orange   0.75      2      2
2     banana  yellow   0.35      3      3
3  raspberry    pink   0.05      4      4

In [13]:
grader.check("q1b")

q1b results: All test cases passed!

### Q2 使用`.drop()`删除新增的rank1和rank2列

In [14]:
fruit_info_original = fruit_info.drop(['rank1', 'rank2'], axis=1)
fruit_info_original

       fruit   color  price
0      apple     red   1.00
1     orange  orange   0.75
2     banana  yellow   0.35
3  raspberry    pink   0.05

In [15]:
grader.check("q2")

q2 results: All test cases passed!

### Q3 使用`.rename()`将fruit_info_original中的列名重命名为大写开头的单词

In [16]:
fruit_info_caps = fruit_info_original.rename(str.capitalize, axis='columns')
fruit_info_caps

       Fruit   Color  Price
0      apple     red   1.00
1     orange  orange   0.75
2     banana  yellow   0.35
3  raspberry    pink   0.05

In [17]:
grader.check("q3")

q3 results: All test cases passed!

In [18]:
file_path = 'data/namesbystate_ca.txt.gz'
column_labels = ['State', 'Sex', 'Year', 'Name', 'Count']

babynames = pd.read_csv(file_path, names=column_labels)

In [19]:
len(babynames)

407428

In [20]:
babynames.head()

  State Sex  Year      Name  Count
0    CA   F  1910      Mary    295
1    CA   F  1910     Helen    239
2    CA   F  1910   Dorothy    220
3    CA   F  1910  Margaret    163
4    CA   F  1910   Frances    134

### Q4a 用`.loc`选择`Name`和`Year`列

In [21]:
name_and_year = babynames.loc[:,['Name', 'Year']]
name_and_year[:5]

       Name  Year
0      Mary  1910
1     Helen  1910
2   Dorothy  1910
3  Margaret  1910
4   Frances  1910

In [22]:
grader.check("q4a")

q4a results: All test cases passed!

### Q4b 用`[]`完成同样的选择

In [23]:
name_and_year = babynames[['Name', 'Year']]
name_and_year[:5]

       Name  Year
0      Mary  1910
1     Helen  1910
2   Dorothy  1910
3  Margaret  1910
4   Frances  1910

### Q5 使用布尔数组，选择2000年计数大于3000的名字；可使用`[]`或`.loc`完成

In [24]:
result = babynames[(babynames['Year'] == 2000) & (babynames['Count'] > 3000)]
result.head()

       State Sex  Year     Name  Count
342440    CA   M  2000   Daniel   4342
342441    CA   M  2000  Anthony   3840
342442    CA   M  2000     Jose   3804
342443    CA   M  2000   Andrew   3600
342444    CA   M  2000  Michael   3572

In [25]:
grader.check("q5")

q5 results: All test cases passed!

### Q6a 使用`.str.get`在“babynames”中添加一个名为“First Letter”的列，其中包含每个婴儿名字的第一个字母

In [26]:
babynames['First Letter'] = babynames['Name'].str.get(0)
babynames

       State Sex  Year      Name  Count First Letter
0         CA   F  1910      Mary    295            M
1         CA   F  1910     Helen    239            H
2         CA   F  1910   Dorothy    220            D
3         CA   F  1910  Margaret    163            M
4         CA   F  1910   Frances    134            F
...      ...  ..   ...       ...    ...          ...
407423    CA   M  2022   Zayvier      5            Z
407424    CA   M  2022       Zia      5            Z
407425    CA   M  2022      Zora      5            Z
407426    CA   M  2022    Zuriel      5            Z
407427    CA   M  2022      Zylo      5            Z

[407428 rows x 6 columns]

In [27]:
grader.check("q6a")

q6a results: All test cases passed!

### Q6b 计算2022年，有多少名字是以A开头的

In [28]:
babynames_2022 = babynames[babynames['Year'] == 2022]
just_A_names_2022 = babynames_2022[babynames_2022['First Letter'] == 'A']
number_A_names = just_A_names_2022['Count'].sum()
number_A_names

55489

In [29]:
grader.check("q6b")

q6b results: All test cases passed!