In [1]:
import pandas as pd

## dataframe 的索引
**dataframe是共享相同索引（index）、相同长度的序列（列）的集合**

In [2]:
elections = pd.read_csv("data/elections.csv")
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [3]:
elections.index

RangeIndex(start=0, stop=182, step=1)

In [4]:
elections = pd.read_csv("data/elections.csv", index_col="Candidate")

In [5]:
elections.index

Index(['Andrew Jackson', 'John Quincy Adams', 'Andrew Jackson',
       'John Quincy Adams', 'Andrew Jackson', 'Henry Clay', 'William Wirt',
       'Hugh Lawson White', 'Martin Van Buren', 'William Henry Harrison',
       ...
       'Darrell Castle', 'Donald Trump', 'Evan McMullin', 'Gary Johnson',
       'Hillary Clinton', 'Jill Stein', 'Joseph Biden', 'Donald Trump',
       'Jo Jorgensen', 'Howard Hawkins'],
      dtype='object', name='Candidate', length=182)

In [14]:
elections.loc['Andrew Jackson']

                Year                  Party  Popular vote Result          %
Candidate
Andrew Jackson  1824  Democratic-Republican        151271   loss  57.210122
Andrew Jackson  1828             Democratic        642806    win  56.203927
Andrew Jackson  1832             Democratic        702735    win  54.574789

In [15]:
elections.loc[['Andrew Jackson', 'Jill Stein']]

                Year                  Party  Popular vote Result          %
Candidate
Andrew Jackson  1824  Democratic-Republican        151271   loss  57.210122
Andrew Jackson  1828             Democratic        642806    win  56.203927
Andrew Jackson  1832             Democratic        702735    win  54.574789
Jill Stein      2012                  Green        469627   loss   0.365199
Jill Stein      2016                  Green       1457226   loss   1.073699

重置索引reset_index

In [25]:
elections.reset_index(inplace=True)
# 参数inplace=True：在原地操作而不是新建一个副本，默认为False？
# 为True时不会输出，默认时会输出数据

设置索引set_index

In [26]:
elections.set_index('Candidate', inplace=True)

In [27]:
elections

,index,Year,Party,Popular vote,Result,%
Candidate,,,,,,
Andrew Jackson,0,1824,Democratic-Republican,151271,loss,57.210122
John Quincy Adams,1,1824,Democratic-Republican,113142,win,42.789878
Andrew Jackson,2,1828,Democratic,642806,win,56.203927
John Quincy Adams,3,1828,National Republican,500897,loss,43.796073
Andrew Jackson,4,1832,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
Jill Stein,177,2016,Green,1457226,loss,1.073699
Joseph Biden,178,2020,Democratic,81268924,win,51.311515
Donald Trump,179,2020,Republican,74216154,loss,46.858542
Jo Jorgensen,180,2020,Libertarian,1865724,loss,1.177979
Howard Hawkins,181,2020,Green,405035,loss,0.255731

### 使用列表和列名创建dataframe
pd.DataFrame(列表，列名columns)

In [28]:
pd.DataFrame([1, 2, 3], columns=['Numbers'])

   Numbers
0        1
1        2
2        3

**传递多个列表的形式实际是以行的形式，一个列表表示一行，列表长度==序列数，列表个数==行数**

In [30]:
pd.DataFrame([[1, 'a'], [2, 'b'], [3, 'c']], columns=['Numbers', 'Letters'])

   Numbers Letters
0        1       a
1        2       b
2        3       c

### 使用字典创建dataframe
{"键1"：[值1、、、], "键2" : [值2、、、]}
键数是列数，值数是行数

In [34]:
pd.DataFrame({"Fruit" : ["Strawberry", "Orange", "Peach"],
              "Price": [5.49, 3.99, 1.99]
              })

        Fruit  Price
0  Strawberry   5.49
1      Orange   3.99
2       Peach   1.99

### 使用Series创建dataframe
先创建多个series：pd.Series(列表，索引index)<br>
将多个series合并：pd.DataFrame({"列名1":series1, "列名2":series2})

In [36]:
s_a = pd.Series(["a1", "a2", "a3"], index=["r1", "r2", "r3"])
s_b = pd.Series(["b1", "b2", "b3"], index=["r1", "r2", "r3"])

In [37]:
pd.DataFrame({"A-column": s_a, "B-column": s_b})

   A-column B-column
r1       a1       b1
r2       a2       b2
r3       a3       b3

In [40]:
elections.head()

,index,Year,Party,Popular vote,Result,%
Candidate,,,,,,
Andrew Jackson,0,1824,Democratic-Republican,151271,loss,57.210122
John Quincy Adams,1,1824,Democratic-Republican,113142,win,42.789878
Andrew Jackson,2,1828,Democratic,642806,win,56.203927
John Quincy Adams,3,1828,National Republican,500897,loss,43.796073
Andrew Jackson,4,1832,Democratic,702735,win,54.574789

In [41]:
elections.head

<bound method NDFrame.head of                    index  Year                  Party  Popular vote Result  \
Candidate
Andrew Jackson         0  1824  Democratic-Republican        151271   loss
John Quincy Adams      1  1824  Democratic-Republican        113142    win
Andrew Jackson         2  1828             Democratic        642806    win
John Quincy Adams      3  1828    National Republican        500897   loss
Andrew Jackson         4  1832             Democratic        702735    win
...                  ...   ...                    ...           ...    ...
Jill Stein           177  2016                  Green       1457226   loss
Joseph Biden         178  2020             Democratic      81268924    win
Donald Trump         179  2020             Republican      74216154   loss
Jo Jorgensen         180  2020            Libertarian       1865724   loss
Howard Hawkins       181  2020                  Green        405035   loss

                           %
Candidate
Andrew Jackson     57.210122
John Quincy Adams  42.789878
Andrew Jackson     56.203927
John Quincy Adams  43.796073
Andrew Jackson     54.574789
...                      ...
Jill Stein          1.073699
Joseph Biden       51.311515
Donald Trump       46.858542
Jo Jorgensen        1.177979
Howard Hawkins      0.255731

[182 rows x 6 columns]>

## dataframe的loc和iloc
**loc和iloc都是用来获取dataframe的行和列的**<br>
df.loc[行索引, 列索引]：使用行和列的**标签**来获取数据，<br>
df.iloc[行索引, 列索引]：使用行和列的**整数位置**来获取数据<br>
loc可以只提供行，只提供列时的格式：loc[:,'']；<br>
iloc同理<br>
### **索引可以用列表、切片、单独值共三种方式提供**
iloc，行索引不受index设置的影响，列索引时0是从index列的后一列开始算<br>

In [50]:
elections.loc['Andrew Jackson', 'Party']

Candidate
Andrew Jackson       Democratic-Republican
John Quincy Adams    Democratic-Republican
Andrew Jackson                  Democratic
John Quincy Adams      National Republican
Andrew Jackson                  Democratic
                             ...
Jill Stein                           Green
Joseph Biden                    Democratic
Donald Trump                    Republican
Jo Jorgensen                   Libertarian
Howard Hawkins                       Green
Name: Party, Length: 182, dtype: object

In [51]:
elections.loc[['Andrew Jackson', 'Jill Stein'], 'Party':'%']

                                Party  Popular vote Result          %
Candidate
Andrew Jackson  Democratic-Republican        151271   loss  57.210122
Andrew Jackson             Democratic        642806    win  56.203927
Andrew Jackson             Democratic        702735    win  54.574789
Jill Stein                      Green        469627   loss   0.365199
Jill Stein                      Green       1457226   loss   1.073699

In [57]:
elections.loc[['Andrew Jackson', 'Jill Stein'], 'Party']

Candidate
Andrew Jackson    Democratic-Republican
Andrew Jackson               Democratic
Andrew Jackson               Democratic
Jill Stein                        Green
Jill Stein                        Green
Name: Party, dtype: object

In [67]:
elections.set_index('Candidate', inplace=True)

In [76]:
elections.iloc[0:2, 0]

Candidate
Andrew Jackson       1824
John Quincy Adams    1824
Name: Year, dtype: int64

In [72]:
elections.head()

                   Year                  Party  Popular vote Result          %
Candidate
Andrew Jackson     1824  Democratic-Republican        151271   loss  57.210122
John Quincy Adams  1824  Democratic-Republican        113142    win  42.789878
Andrew Jackson     1828             Democratic        642806    win  56.203927
John Quincy Adams  1828    National Republican        500897   loss  43.796073
Andrew Jackson     1832             Democratic        702735    win  54.574789